// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {waLog} from '../models';

export function Greet(arg1:string):Promise<string>;

export function ShowWhatsapp():Promise<waLog.Logger>;

export function StartWhatsapp():Promise<void>;
