// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ShowWhatsapp() {
  return window['go']['main']['App']['ShowWhatsapp']();
}

export function StartWhatsapp() {
  return window['go']['main']['App']['StartWhatsapp']();
}

export function WhatsappEvent(arg1) {
  return window['go']['main']['App']['WhatsappEvent'](arg1);
}
